language: node_js
node_js:
  - 11
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then NODE_ENV=test npm test; fi
addons:
  sonarcloud:
    organization: "florentdev-github"
script:
  - sonar-scanner -Dsonar.javascript.lcov.reportPaths=./build/reports/coverage/server-tests/lcov.info

before_deploy:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package
script:
#  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.0.0-M3-release.zip -O dependency-check.zip
#  - unzip dependency-check.zip
#  - sh ./dependency-check/bin/dependency-check.sh --project DependencyTest --out . --scan .
  - wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region eu-west-1)
  - docker build -t juiceshop .
  - docker tag juiceshop:latest 555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop
  - docker push 555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  bucket: "juiceshopbucket"

addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
     - ./report

script:
  - sudo mkdir report && sudo chown 1000:1000 report
  - docker run -t -v $(pwd)/report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://http://52.214.27.145:32768 -r testreport.html || true
