language: node_js
node_js:
  - 11
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then NODE_ENV=test npm test; fi

before_deploy:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region eu-west-1)
  - docker build -t juiceshop .
  - docker tag juiceshop:latest 555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop
  - docker push 555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=555107934542.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:latest"
